version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: ./Dockerfile
  #   volumes:
  #     - ./client/:/client
  #     - /client/node_modules
  #   image: fastcup-chrome-extension-frontend
  #   container_name: fastcup-chrome-extension-frontend
  #   restart: always

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server/:/server
      - /server/node_modules
    image: fastcup-chrome-extension-server
    container_name: fastcup-chrome-extension-server
    ports:
      - "3000:3000"
      # - "9229:9229"
    restart: always
