version: '3'

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 80:80

  extension:
    tty: true
    image: node:20-alpine3.16
    volumes:
      - .:/var/www/extension
      - /var/www/extension/node_modules
    container_name: fastcup-enhancer-frontend
    restart: always
